name: Build

on:
  workflow_dispatch:
    inputs:
      useCache:
        description: Use GHA cache
        type: boolean
        required: false
        default: true
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "tests/**"
      - "*.sh"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "tests/**"
      - "*.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_manylinux:
    name: ${{ matrix.policy }}_${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    permissions:
      actions: write # this permission is needed to delete cache
    strategy:
      fail-fast: false
      matrix:
        include:
          - policy: manylinux_2_28
            platform: x86_64
            runner: ubuntu-24.04
          - policy: manylinux_2_28
            platform: aarch64
            runner: ubuntu-24.04-arm
    env:
      POLICY: ${{ matrix.policy }}
      PLATFORM: ${{ matrix.platform }}
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore cache
        if: github.event_name != 'workflow_dispatch' || fromJSON(github.event.inputs.useCache)
        uses: actions/cache/restore@v4
        with:
          path: .buildx-cache-${{ matrix.policy }}_${{ matrix.platform }}/*
          key: buildx-cache-${{ matrix.policy }}-${{ matrix.platform }}

      - name: Build
        run: ./build.sh

      - name: Delete cache
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          KEY="buildx-cache-${{ matrix.policy }}-${{ matrix.platform }}"
          gh cache delete ${KEY} || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save cache
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/cache/save@v4
        with:
          path: .buildx-cache-${{ matrix.policy }}_${{ matrix.platform }}/*
          key: buildx-cache-${{ matrix.policy }}-${{ matrix.platform }}
